In [1]:
from scipy.misc import imsave, imread, imresize
import numpy as np
import argparse
from keras.models import model_from_yaml
import re
import base64
import pickle
import tensorflow as tf

Using TensorFlow backend.


In [2]:
x = ['O:\\Data\\HORUS\\img_test.png']

filename_queue = tf.train.string_input_producer(['O:\\Data\\HORUS\\img_test.png'])
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)

my_img = tf.image.decode_png('O:\\Data\\HORUS\\img_test.png')

print(my_img)

Tensor("DecodePng:0", shape=(?, ?, ?), dtype=uint8)


In [3]:
#n_img = expand_dims(my_img, 0)
x = imread('O:\\Data\\HORUS\\img_test.png', mode='L')
x = np.invert(x)

# Visualize new array
imsave('resized.png', x)
x = imresize(x,(28,28))

viz = imresize(x,(19,19))
print(viz)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  4  6  8  9  7  5  2  0  0  0  0  0  0  0]
 [ 0  0  1 20 51 64 73 83 83 80 70 51 20  1  0  0  0  0  0]
 [ 0  0  1 32 56 43 29 18 17 25 41 67 78 25  0  0  0  0  0]
 [ 0  0  0  1  1 35 38  0  0  0  0  3 32 60  7  0  0  0  0]
 [ 0  0  0  0  0 39 72  0  0  0  0  0  7 51 18  0  0  0  0]
 [ 0  0  0  0  0 19 86  5  0  0  0  0 12 57 14  0  0  0  0]
 [ 0  0  0  0  0  6 81 18  0  0  0  5 46 55  3  0  0  0  0]
 [ 0  0  0  0  0  3 73 65 38 43 56 72 60 14  0  0  0  0  0]
 [ 0  0  0  0  0  3 68 89 48 45 33 12  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 50 70  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 41 89  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28 91 13  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 18 84 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5 30  7  0  0  0  0

In [4]:
# reshape image data for use in neural network
x = x.reshape(1,28,28,1)

# Convert type to float32
x = x.astype('float32')
# Normalize to prevent issues with model
x /= 255

In [5]:
yaml_file = open('O:\\Data\\HORUS\\model.yaml', 'r')
loaded_model_yaml = yaml_file.read()
yaml_file.close()
loaded_model = model_from_yaml(loaded_model_yaml)

# load weights into new model
loaded_model.load_weights("O:\\Data\\HORUS\\model.h5")
print("Loaded model from disk")

Loaded model from disk


In [6]:
out = loaded_model.predict(x)
print(out)

[[  2.30075466e-03   5.14860207e-04   2.67487695e-03   7.99509115e-04
    9.37447621e-05   2.36581822e-04   1.27193334e-05   2.46512238e-02
    3.53636406e-03   1.32223440e-03   3.63356230e-04   3.32452968e-04
    1.72782945e-03   5.49593940e-03   1.19119868e-04   1.55979674e-02
    7.05913990e-05   2.25704469e-04   2.58736801e-03   6.37947873e-04
    3.71155293e-05   1.85470162e-05   2.25056006e-04   3.86198564e-03
    4.60675405e-03   5.47463834e-01   4.11246787e-04   6.03490218e-04
    5.34914143e-04   1.31586650e-02   4.54346940e-04   2.77195731e-03
    2.15746972e-04   5.10829886e-05   1.82331807e-03   4.01955942e-04
    4.66312631e-04   6.19019702e-05   7.94810941e-04   1.04702194e-04
    3.78799252e-03   4.44862107e-03   1.84681820e-04   6.53301822e-06
    1.37726974e-03   7.77168141e-04   5.96285608e-05   1.02099159e-03
    1.69668434e-04   7.92966632e-04   2.26864545e-03   2.98435718e-01
    1.90422899e-04   3.25415395e-02   1.77123860e-04   8.50100815e-03
    8.83202374e-05  

In [13]:
mapping = pickle.load(open('O:\\Data\\HORUS\\mapping.p', 'rb'))
response = chr(mapping[(int(np.argmax(out, axis=1)[0]))])
print(response)

P
